### ISSUE TITLE
Sending mails with cc / bcc

### ISSUE THREAD

**Issue by bitboxer** [timcraft/mailgunner#9] opened 2015-11-30 11:05 UTC
Sadly sending mails using cc or bcc does not work for us. Can someone confirm this? Or do we do something wrong?

Would love to help you to investigate this and send a PR after we figured out what is wrong.

**Comment by timcraft** [comment] 2016-01-07 14:56
@bitboxer Can you post more details about how you're using the gem and/or a minimal example that reproduces the problem?

**Comment by jimknight** [comment] 2016-01-16 20:01
@bitboxer, I have the same issue. not sure if it's the gem's problem or mailgun (I'm guessing the gem isn't sending it just because i assume mailgun can do this). the recipient messages shows the cc value but mailgun never sends there.

they show this in the log:

  "message": {
    "headers": {
      "to": "jimknight@lavatech.com",
      "message-id": "<hidden>",
      "from": "jimknight@lavatech.com",
      "subject": "test with just copyto"
    },

**Comment by bitboxer** [comment] 2016-01-16 21:41
Sorry to say, but we switched to sending the stuff via smtp. That way we could send stuff via bcc. I think back then I saw that the gem did not send the proper request to mailgun. But I am not 100% sure :cry:

**Comment by timcraft** [comment] 2016-01-20 12:57
@jimknight @bitboxer Fixed in acebb54, v2.2.2 should work correctly.

**Closed by timcraft** 2016-01-20 12:57 UTC

**Comment by bitboxer** [comment] 2016-01-20 13:06
Great! Thank you. I will switch to the gem in the next project we start!
