### ISSUE TITLE
suggest refactoring variable-dependent methods to provide better error-handling

### ISSUE THREAD

**Issue by bergerjac** [timcraft/mailgunner#6] opened 2015-01-22 08:59 UTC
the main issue is that the response code ([ref](https://github.com/timcraft/mailgunner/commit/93304210cd7d6ca1a6a89270009a5ca8ec2a300b#commitcomment-9392559)) is too generic.  this error could be caught within `Mailgunner`, providing more information.

api calls requiring `domain` could be moved to a separate 'internal' class. all calls would be 'routed' through it and 

```ruby
if domain is nil
  # don't send the request
  raise an error # 'domain' variable not set; check your `ENV["MAILGUN_SMTP_LOGIN"]` variable or `Mailgunner::Client` initializer
```

**Comment by timcraft** [comment] 2015-01-27 14:36
@bergerjac Thanks. I think a separate class would be overcomplicating things a bit. The other option is moving it to a method like you've implemented in #7, but that seems a bit too "defensive" and touches a lot of code. The root of the problem is the nil, which ideally shouldn't creep in at all. Having a go at an alternative solution now.

What's the context for when you were originally debugging the problem--are you using the ActionMailer integration or instantiating Mailgunner::Client directly?

**Comment by timcraft** [comment] 2015-01-27 15:51
I've just released v2.1.0 which raises an exception if the domain is not set, should make it easier to debug config problems. Thanks for highlighting the issue!

**Closed by timcraft** 2015-01-27 15:51 UTC

**Comment by bergerjac** [comment] 2015-01-27 15:52
> What's the context for when you were originally debugging the problem

ActionMailer integration

**Comment by timcraft** [comment] 2015-01-27 15:59
@bergerjac Ok thanks. I'm not testing with dotenv, but if you have any further problems I'd recommend following one of the approaches outlined in the [dotenv README](https://github.com/bkeepers/dotenv#note-on-load-order).
